---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t autobnb/wedding -f Dockerfile .

- name: deploy
  image: docker/compose:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker-compose up -d

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
